[Icon Theme]
Name=Kiwori Dark
Comment=A colorful and playful icon theme for Linux desktops (Dark mode fallback)
Inherits=breeze-dark,hicolor
Example=folder

Directories=scalable/apps,scalable/actions,scalable/devices,scalable/places,scalable/mimetypes,scalable/categories,scalable/status,scalable/emblems

[scalable/apps]
Size=256
Context=Applications
Type=Scalable
MinSize=16
MaxSize=512

[scalable/actions]
Size=256
Context=Actions
Type=Scalable
MinSize=16
MaxSize=512

[scalable/devices]
Size=256
Context=Devices
Type=Scalable
MinSize=16
MaxSize=512

[scalable/places]
Size=256
Context=Places
Type=Scalable
MinSize=16
MaxSize=512

[scalable/mimetypes]
Size=256
Context=MimeTypes
Type=Scalable
MinSize=16
MaxSize=512

[scalable/categories]
Size=256
Context=Categories
Type=Scalable
MinSize=16
MaxSize=512

[scalable/status]
Size=256
Context=Status
Type=Scalable
MinSize=16
MaxSize=512

[scalable/emblems]
Size=256
Context=Emblems
Type=Scalable
MinSize=16
MaxSize=512
